---
version: 2.1

jobs:
  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2

    steps:
    - checkout
    - restore_cache:
        keys:
        - my_cache

    - run:
        name: Get ds114_test1_with_freesurfer from OSF
        command: |
          mkdir -p ${HOME}/data;
          if [[ ! -d ${HOME}/data/ds114_test1_with_freesurfer ]]; then
            wget -c -O ${HOME}/ds114_test1_with_freesurfer.tar.gz "https://osf.io/download/y4q8a/"
            tar xfz ${HOME}/ds114_test1_with_freesurfer.tar.gz -C ${HOME}/data
            ls -la
          fi
    - run:
        name: Build Docker image
        command: |
          if [[ -e ${HOME}/docker/image.tar ]]; \
            then docker load -i ${HOME}/docker/image.tar;
          fi
          git describe --tags --always > version
          docker build -t bids/${CIRCLE_PROJECT_REPONAME,,} .
          mkdir -p ${HOME}/docker
          docker save "bids/${CIRCLE_PROJECT_REPONAME,,}" > ${HOME}/docker/image.tar

    - save_cache:
        key: my_cache
        paths:
        - ~/docker
        - ~/data

    - persist_to_workspace:
        root: /home/circleci
        paths:
        - data/ds114_test1_with_freesurfer
        - docker/image.tar

  test:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: docker load -i /tmp/workspace/docker/image.tar

    - run:
        name: print version
        command: |
          docker run -ti --rm --read-only \
            -v /tmp/workspace/data/ds114_test1_with_freesurfer:/bids_dataset \
            -v ${HOME}/outputs1:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} --version
    - run:
        name: run participant 1
        command: |
          docker run -ti --rm --read-only \
            -v /tmp/workspace/data/ds114_test1_with_freesurfer:/bids_dataset \
            -v ${HOME}/outputs1:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant --participant_label 01
        no_output_timeout: 6h

  deploy:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: docker load -i /tmp/workspace/docker/image.tar

    - run:
        command: |
          if [[ -n "$DOCKER_PASS" ]]; then
            echo "${DOCKER_PASS}" | docker login -u ${DOCKER_USER} --password-stdin && \
            docker push bids/${CIRCLE_PROJECT_REPONAME}:latest
            if [[ -n "${CIRCLE_TAG}" ]]; then
              docker tag bids/${CIRCLE_PROJECT_REPONAME} bids/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG
              docker push bids/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG;
            fi
          fi

workflows:
  build-test-deploy:
    jobs:
    - build
    - test:
        requires:
        - build
    - deploy:
        requires:
        - test
        filters:
          tags:
            only: /.*/
